USE NQViewer
GO
--
-- Vertical non-aggregated union of all subservice ratings stats.
--
IF (OBJECT_ID('SUBSERVICE_OFFICE') IS NOT NULL) DROP VIEW SUBSERVICE_OFFICE
GO 
CREATE VIEW SUBSERVICE_OFFICE AS 
SELECT 
	o.OFFICEGUID,
	o.OFFICE_NR,

	allTypes.SRC,
	CASE allTypes.SRC 
		WHEN 1 THEN 'ST'
		WHEN 2 THEN 'C'
		WHEN 3 THEN 'U'
		END AS [SRC_NAME],
	allTypes.ITEM_NR,

	allTypes.FEEDBACK_TOTAL,
	allTypes.FEEDBACK_AVG,

	allTypes.FEEDBACK_1,
	allTypes.FEEDBACK_2,
	allTypes.FEEDBACK_3,
	allTypes.FEEDBACK_4,
	allTypes.FEEDBACK_5

FROM OFFICE_INFO o

LEFT OUTER JOIN (
	
	SELECT 
		1 AS [SRC],
		OFFICEGUID,
		OFFICE_NR,
		SERVICETYPE_NR				AS [ITEM_NR],
		FEEDBACK_TOTAL,
		FEEDBACK_AVG,
		FEEDBACK_1,
		FEEDBACK_2,
		FEEDBACK_3,
		FEEDBACK_4,
		FEEDBACK_5
	FROM SUBSERVICE_SERVICETYPE_RATING 

	UNION ALL 
	SELECT 
		2 AS [SRC],
		OFFICEGUID,
		OFFICE_NR,
		CASHIER_NR					AS [ITEM_NR],
		FEEDBACK_TOTAL,
		FEEDBACK_AVG,
		FEEDBACK_1,
		FEEDBACK_2,
		FEEDBACK_3,
		FEEDBACK_4,
		FEEDBACK_5
	FROM SUBSERVICE_CASHIER_RATING 
	
	UNION ALL
	SELECT 
		3 AS [SRC],
		OFFICEGUID,
		OFFICE_NR,
		USER_NR					AS [ITEM_NR],
		FEEDBACK_TOTAL,
		FEEDBACK_AVG,
		FEEDBACK_1,
		FEEDBACK_2,
		FEEDBACK_3,
		FEEDBACK_4,
		FEEDBACK_5
	FROM SUBSERVICE_USER_RATING 
	
) AS allTypes

ON allTypes.OFFICEGUID = o.OFFICEGUID

GO

SELECT * FROM SUBSERVICE_OFFICE