USE NQViewer
GO
-- 
-- CASHIER subservice entries
--
IF (OBJECT_ID('SUBSERVICE_CASHIER') IS NOT NULL) DROP VIEW SUBSERVICE_CASHIER 
GO
CREATE VIEW SUBSERVICE_CASHIER AS
SELECT
	base.OFFICEGUID,
	base.OFFICE_NR,
	base.CASHIER_NR,

	-- Subservice entry 	
	subs.SERVICETYPE_NR,	
	subs.USER_NR,	
	subs.SUBSERVICE_NR, 
	subs.SUBSERVICE_NAME, 
	subs.FACTOR,
	subs.SERVICE_TIME,
	subs.SUBSERVICE_TIME,
	subs.TRACK_NR

FROM CASHIER_QUEUE_INFO base

LEFT OUTER JOIN SUBSERVICE_QUEUE_INFO subs ON
	subs.OFFICEGUID = base.OFFICEGUID AND 
	subs.CASHIER_NR = base.CASHIER_NR
	
WHERE base.CASHIER_NR > 0
GO




