USE NQViewer
GO
--
-- SERVICE TYPE aggregated subservice entries, focusing on customer feedback (ssnr 101-105)
--
IF (OBJECT_ID('SUBSERVICE_SERVICETYPE_RATING') IS NOT NULL) DROP VIEW SUBSERVICE_SERVICETYPE_RATING
GO
CREATE VIEW SUBSERVICE_SERVICETYPE_RATING AS
SELECT
	OFFICEGUID,
	OFFICE_NR,
	SERVICETYPE_NR,

	COUNT(SUBSERVICE_NR)							AS [FEEDBACK_TOTAL],
	AVG(CONVERT(FLOAT, SUBSERVICE_NR - 100))		AS [FEEDBACK_AVG],

	-- Feedback per grade 101-105
	COUNT(CASE WHEN SUBSERVICE_NR = 101 THEN 1 ELSE NULL END) AS [FEEDBACK_1],
	COUNT(CASE WHEN SUBSERVICE_NR = 102 THEN 1 ELSE NULL END) AS [FEEDBACK_2],
	COUNT(CASE WHEN SUBSERVICE_NR = 103 THEN 1 ELSE NULL END) AS [FEEDBACK_3],
	COUNT(CASE WHEN SUBSERVICE_NR = 104 THEN 1 ELSE NULL END) AS [FEEDBACK_4],
	COUNT(CASE WHEN SUBSERVICE_NR = 105 THEN 1 ELSE NULL END) AS [FEEDBACK_5]

FROM SUBSERVICE_SERVICETYPE
WHERE SUBSERVICE_NR BETWEEN 101 AND 105		-- SS Rating is only interested in SS values 101-105
GROUP BY 
	OFFICEGUID, 
	OFFICE_NR,
	SERVICETYPE_NR
GO
