USE NQViewer
GO

IF (OBJECT_ID('CASHIER_QUEUE_INFO_CUST') IS NOT NULL) DROP VIEW CASHIER_QUEUE_INFO_CUST
GO

CREATE VIEW CASHIER_QUEUE_INFO_CUST AS
SELECT 	
	a.OFFICE_NR,
	a.OFFICEGUID,
	a.CASHIER_NR,

-- Total service time 
	SUM(cust.SERVICE_TIME) AS [TOT_SERVICE_TIME]

FROM CASHIER_QUEUE_INFO a
LEFT OUTER JOIN CUSTOMER_QUEUE_INFO cust
	ON a.CASHIER_NR = cust.CASHIER_NR 
	AND a.OFFICEGUID = cust.OFFICEGUID
WHERE a.CASHIER_NR > 0
GROUP BY 
	a.OFFICE_NR, 
	a.OFFICEGUID, 
	a.CASHIER_NR 