USE NQViewer
GO
-- 
-- USER subservice entries
--
IF (OBJECT_ID('SUBSERVICE_USER') IS NOT NULL) DROP VIEW SUBSERVICE_USER 
GO
CREATE VIEW SUBSERVICE_USER AS
SELECT
	base.OFFICEGUID,
	base.OFFICE_NR,
	base.USER_NR,

	-- Subservice entry 	
	subs.SERVICETYPE_NR,	
	subs.CASHIER_NR,	
	subs.SUBSERVICE_NR, 
	subs.SUBSERVICE_NAME, 
	subs.FACTOR,
	subs.SERVICE_TIME,
	subs.SUBSERVICE_TIME,
	subs.TRACK_NR

FROM USER_QUEUE_INFO base

LEFT OUTER JOIN SUBSERVICE_QUEUE_INFO subs ON
	subs.OFFICEGUID = base.OFFICEGUID AND 
	subs.USER_NR	= base.USER_NR
	
WHERE base.USER_NR > 0
GO




