USE NQViewer
GO
--
-- Non-aggregated, vertical union of all values common to the ST/C/U ext views. 
--
IF (OBJECT_ID('OFFICE_COMMONS_UNION') IS NOT NULL) DROP VIEW OFFICE_COMMONS_UNION
GO
CREATE VIEW OFFICE_COMMONS_UNION AS
SELECT * FROM (
	SELECT 
		OFFICEGUID, 
		OFFICE_NR,
		1 AS [SRC],
		SERVICETYPE_NR				AS [ITEM_NR],
		WAITING_CUSTOMERS_TOT,
		WAITING_CUSTOMERS_MQ,
		WAITING_CUSTOMERS_SQ,
		WAITING_CUSTOMERS_BQ,		
		AVG_WAITING_TIME_TOT,
		AVG_WAITING_TIME_MQ,
		AVG_WAITING_TIME_SQ,
		AVG_WAITING_TIME_BQ,
		LONGEST_WT_SECONDS_TOT,
		LONGEST_WT_SECONDS_MQ,
		LONGEST_WT_SECONDS_SQ,
		LONGEST_WT_SECONDS_BQ,
		SERVED_CUSTOMERS_TOT,
		SERVED_CUSTOMERS_MQ,
		SERVED_CUSTOMERS_SQ,
		SERVED_CUSTOMERS_BQ,
		AVG_SERVICE_TIME_TOT,
		AVG_SERVICE_TIME_MQ,
		AVG_SERVICE_TIME_SQ,
		AVG_SERVICE_TIME_BQ,
		LONGEST_SERVICE_TIME		
	FROM SERVICETYPE_QUEUE_INFO_EXT

	UNION ALL SELECT 
		OFFICEGUID,
		OFFICE_NR,
		2 AS [SRC],
		CASHIER_NR					AS [ITEM_NR], 
		WAITING_CUSTOMERS_TOT,
		WAITING_CUSTOMERS_MQ,
		WAITING_CUSTOMERS_SQ,
		WAITING_CUSTOMERS_BQ,		
		AVG_WAITING_TIME_TOT,
		AVG_WAITING_TIME_MQ,
		AVG_WAITING_TIME_SQ,
		AVG_WAITING_TIME_BQ,
		LONGEST_WT_SECONDS_TOT,
		LONGEST_WT_SECONDS_MQ,
		LONGEST_WT_SECONDS_SQ,
		LONGEST_WT_SECONDS_BQ,
		SERVED_CUSTOMERS_TOT,
		SERVED_CUSTOMERS_MQ,
		SERVED_CUSTOMERS_SQ,
		SERVED_CUSTOMERS_BQ,
		AVG_SERVICE_TIME_TOT,
		AVG_SERVICE_TIME_MQ,
		AVG_SERVICE_TIME_SQ,
		AVG_SERVICE_TIME_BQ,
		LONGEST_SERVICE_TIME		
	FROM CASHIER_QUEUE_INFO_EXT
  
	UNION ALL SELECT 
		OFFICEGUID,
		OFFICE_NR,	
		3 AS [SRC],
		USER_NR						AS [ITEM_NR], 
		WAITING_CUSTOMERS_TOT,
		WAITING_CUSTOMERS_MQ,
		WAITING_CUSTOMERS_SQ,
		WAITING_CUSTOMERS_BQ,		
		AVG_WAITING_TIME_TOT,
		AVG_WAITING_TIME_MQ,
		AVG_WAITING_TIME_SQ,
		AVG_WAITING_TIME_BQ,
		LONGEST_WT_SECONDS_TOT,
		LONGEST_WT_SECONDS_MQ,
		LONGEST_WT_SECONDS_SQ,
		LONGEST_WT_SECONDS_BQ,
		SERVED_CUSTOMERS_TOT,
		SERVED_CUSTOMERS_MQ,
		SERVED_CUSTOMERS_SQ,
		SERVED_CUSTOMERS_BQ,
		AVG_SERVICE_TIME_TOT,
		AVG_SERVICE_TIME_MQ,
		AVG_SERVICE_TIME_SQ,
		AVG_SERVICE_TIME_BQ,
		LONGEST_SERVICE_TIME		
	FROM USER_QUEUE_INFO_EXT
) AS commons
ORDER BY commons.OFFICE_NR, commons.SRC, commons.ITEM_NR
GO



